name: LFPAnalysis
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - h5io
  - mne>=1.6
  - numpy>=1.24
  - openpyxl>=3.1
  - pandas>=2.0
  - python-levenshtein>=0.25
  - pyyaml>=6.0
  - scipy>=1.11
  - pip:
      - -e .
