"""Stable public exports for the beginner-facing LFPAnalysis workflow API."""

from .builders import (
    build_analysis_config,
    build_basic_pipeline_config,
    build_event_locked_pipeline_config,
    build_prep_config,
    build_spectral_pipeline_config,
    build_tutorial_pipeline_config,
)
from .config import (
    WORKING_DTYPE,
    AnalysisConfig,
    ArtifactConfig,
    BaselineConfig,
    ElectrodeConfig,
    EpochConfig,
    LoadConfig,
    PipelineConfig,
    PrepConfig,
    ReferenceConfig,
    SpectralConfig,
    SyncConfig,
    TfrConfig,
    analysis_config_from_pipeline,
    prep_config_from_pipeline,
)
from .exceptions import (
    ConfigurationError,
    DataContractError,
    LFPAnalysisError,
    MissingDependencyError,
)
from .prep import run_prep, synchronize_lfp
from .results import AnalysisResult, PipelineResult, PrepResult
from .schemas import (
    ARTIFACT_EVENT_COLUMNS,
    BASELINE_SUMMARY_COLUMNS,
    ELECTRODE_OPTIONAL_COLUMNS,
    ELECTRODE_REQUIRED_COLUMNS,
    SYNC_SUMMARY_COLUMNS,
    TFR_METADATA_COLUMNS,
)
from .workflow import (
    baseline_lfp,
    compute_spectral_features,
    compute_tfr_features,
    detect_artifacts,
    load_electrode_metadata,
    load_lfp,
    make_epochs,
    preprocess_lfp,
    run_analysis,
    run_pipeline,
)

__all__ = [
    "ARTIFACT_EVENT_COLUMNS",
    "AnalysisConfig",
    "AnalysisResult",
    "ArtifactConfig",
    "BASELINE_SUMMARY_COLUMNS",
    "BaselineConfig",
    "ELECTRODE_OPTIONAL_COLUMNS",
    "ELECTRODE_REQUIRED_COLUMNS",
    "ElectrodeConfig",
    "EpochConfig",
    "SYNC_SUMMARY_COLUMNS",
    "TFR_METADATA_COLUMNS",
    "SyncConfig",
    "TfrConfig",
    "PrepConfig",
    "PrepResult",
    "build_analysis_config",
    "build_basic_pipeline_config",
    "build_event_locked_pipeline_config",
    "build_prep_config",
    "build_spectral_pipeline_config",
    "build_tutorial_pipeline_config",
    "ConfigurationError",
    "DataContractError",
    "LFPAnalysisError",
    "LoadConfig",
    "MissingDependencyError",
    "PipelineConfig",
    "PipelineResult",
    "ReferenceConfig",
    "SpectralConfig",
    "WORKING_DTYPE",
    "analysis_config_from_pipeline",
    "baseline_lfp",
    "compute_spectral_features",
    "compute_tfr_features",
    "detect_artifacts",
    "load_electrode_metadata",
    "load_lfp",
    "make_epochs",
    "prep_config_from_pipeline",
    "preprocess_lfp",
    "run_analysis",
    "run_pipeline",
    "run_prep",
    "synchronize_lfp",
]
