title: LFPAnalysis Book
author: Salman E. Qasim
only_build_toc_files: true

execute:
  execute_notebooks: cache
  timeout: 1200
  allow_errors: false
  remove_code_source: false
  remove_cell_outputs: false

repository:
  url: https://github.com/seqasim/LFPAnalysis
  path_to_book: LFPAnalysisBook
  branch: main

launch_buttons:
  notebook_interface: jupyterlab
  binderhub_url: ""
  colab_url: ""
  thebe: false

html:
  use_issues_button: true
  use_repository_button: true
  use_edit_page_button: false

bibtex_bibfiles:
  - references.bib

sphinx:
  config:
    nb_execution_raise_on_error: true
